### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by deevashwer** [benjaminhmtan/wildcardHElib#1]
I'm getting the following error on compiling the code. I've NTL, GMP, and HElib configured and installed.

<img width="717" alt="screen shot 2017-12-09 at 11 22 54 pm" src="https://user-images.githubusercontent.com/23222086/33796459-fe0ea964-dd37-11e7-89f1-3e14290b6cf0.png">

Is there some dependency that I'm missing here? Any help would be appreciated.

**Comment by benjaminhmtan** [comment]
Thanks for the feedback! I found that the code was an older version and I have updated the repository.
